version: '3.7'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
    ports:
      - "8001:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U docker"]
      interval: 10s
      timeout: 5s
      retries: 5

  queue:
    image: rabbitmq:3
    restart: always

  web:
    build:
      context: .
      dockerfile: backend.dockerfile
    image: "song-pulse"
    depends_on:
      db:
        condition: service_healthy
      worker
    environment:
      - DATABASE_URL=postgres://docker:docker@db:5432/docker
      - SPOTIPY_CLIENT_ID=bcff380514c34d9c9e9c0f075368622f
      - SPOTIPY_CLIENT_SECRET=06abee92ed8e4b8180f1de73e6244ef9
    ports:
      - "8080:8080"

  worker:
    build:
      context: .
      dockerfile: celery.dockerfile
    image: 'song-pulse-worker'
    depends_on:
      db:
        condition: service_healthy
      queue
    environment:
      - DATABASE_URL=postgres://docker:docker@db:5432/docker