version: '3.7'
services:
  web:
    build: .
    image: "dikohl/song-pulse"
    environment:
      - DATABASE_URL=postgres://docker:docker@db:5432/docker
    ports:
      - "8080:8080"
  db:
    image: "dikohl/postgres"
    ports:
      - "8001:5432"