"""temp_threshold to temp_baseline

Revision ID: 0256de853a95
Revises: fdd2f1c3818b
Create Date: 2020-05-14 10:24:23.813807

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0256de853a95'
down_revision = 'fdd2f1c3818b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('setting', sa.Column('temp_baseline', sa.Float(), nullable=True))
    op.drop_column('setting', 'temp_threshold')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('setting', sa.Column('temp_threshold', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('setting', 'temp_baseline')
    # ### end Alembic commands ###
