"""added spotify table

Revision ID: 200a6d6bf142
Revises: f117c270e465
Create Date: 2020-06-29 13:32:43.927533

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '200a6d6bf142'
down_revision = 'f117c270e465'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spotify',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('refresh_token', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_spotify_id'), 'spotify', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_spotify_id'), table_name='spotify')
    op.drop_table('spotify')
    # ### end Alembic commands ###
