"""adding a table for tendencies

Revision ID: 54745d110fb6
Revises: bd7ef1dd11c6
Create Date: 2020-07-21 09:57:52.546148

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '54745d110fb6'
down_revision = 'bd7ef1dd11c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tendency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.BigInteger(), nullable=True),
    sa.Column('eda', sa.Integer(), nullable=True),
    sa.Column('mean_rr', sa.Integer(), nullable=True),
    sa.Column('prr_20', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tendency_id'), 'tendency', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tendency_id'), table_name='tendency')
    op.drop_table('tendency')
    # ### end Alembic commands ###
