"""added prr_threshold and qtable

Revision ID: 6790c6d7fa8a
Revises: 0256de853a95
Create Date: 2020-05-28 10:40:03.530945

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '6790c6d7fa8a'
down_revision = '0256de853a95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qtable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=True),
    sa.Column('data', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['participant_id'], ['participant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qtable_id'), 'qtable', ['id'], unique=False)
    op.create_index(op.f('ix_qtable_participant_id'), 'qtable', ['participant_id'], unique=False)
    op.alter_column('sensor', 'frequency',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('setting', sa.Column('prr_threshold', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('setting', 'prr_threshold')
    op.alter_column('sensor', 'frequency',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_qtable_participant_id'), table_name='qtable')
    op.drop_index(op.f('ix_qtable_id'), table_name='qtable')
    op.drop_table('qtable')
    # ### end Alembic commands ###
