"""added name to recording, removed total time

Revision ID: 87fc4a5f0e42
Revises: dc4f12ec96da
Create Date: 2020-04-20 14:50:27.941802

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '87fc4a5f0e42'
down_revision = 'dc4f12ec96da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('file_recording_id_fkey', 'file', type_='foreignkey')
    op.create_foreign_key(None, 'file', 'recording', ['recording_id'], ['id'])
    op.create_index(op.f('ix_playlist_participant_id'), 'playlist', ['participant_id'], unique=False)
    op.create_index(op.f('ix_playlist_type'), 'playlist', ['type'], unique=False)
    op.drop_constraint('playlist_participant_id_fkey', 'playlist', type_='foreignkey')
    op.create_foreign_key(None, 'playlist', 'participant', ['participant_id'], ['id'])
    op.add_column('recording', sa.Column('name', sa.String(), nullable=True))
    op.add_column('sensor', sa.Column('frequency', sa.Integer(), nullable=False))
    op.drop_constraint('recording_participant_id_fkey', 'recording', type_='foreignkey')
    op.create_foreign_key(None, 'recording', 'participant', ['participant_id'], ['id'])
    op.drop_column('recording', 'total_time')
    op.drop_constraint('result_run_id_fkey', 'result', type_='foreignkey')
    op.create_foreign_key(None, 'result', 'run', ['run_id'], ['id'])
    op.drop_constraint('run_recording_id_fkey', 'run', type_='foreignkey')
    op.create_foreign_key(None, 'run', 'recording', ['recording_id'], ['id'])
    op.drop_constraint('song_playlist_id_fkey', 'song', type_='foreignkey')
    op.create_foreign_key(None, 'song', 'playlist', ['playlist_id'], ['id'])
    op.drop_constraint('value_file_id_fkey', 'value', type_='foreignkey')
    op.create_foreign_key(None, 'value', 'file', ['file_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'value', type_='foreignkey')
    op.create_foreign_key('value_file_id_fkey', 'value', 'file', ['file_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'song', type_='foreignkey')
    op.create_foreign_key('song_playlist_id_fkey', 'song', 'playlist', ['playlist_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'run', type_='foreignkey')
    op.create_foreign_key('run_recording_id_fkey', 'run', 'recording', ['recording_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'result', type_='foreignkey')
    op.create_foreign_key('result_run_id_fkey', 'result', 'run', ['run_id'], ['id'], ondelete='CASCADE')
    op.add_column('recording', sa.Column('total_time', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'recording', type_='foreignkey')
    op.create_foreign_key('recording_participant_id_fkey', 'recording', 'participant', ['participant_id'], ['id'],
                          ondelete='CASCADE')
    op.drop_column('recording', 'name')
    op.drop_constraint(None, 'playlist', type_='foreignkey')
    op.create_foreign_key('playlist_participant_id_fkey', 'playlist', 'participant', ['participant_id'], ['id'],
                          ondelete='CASCADE')
    op.drop_index(op.f('ix_playlist_type'), table_name='playlist')
    op.drop_index(op.f('ix_playlist_participant_id'), table_name='playlist')
    op.drop_constraint(None, 'file', type_='foreignkey')
    op.create_foreign_key('file_recording_id_fkey', 'file', 'recording', ['recording_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
