"""separate counters for min and max range

Revision ID: 96d5888b759f
Revises: 9848e3c12e0f
Create Date: 2020-07-24 10:24:08.682847

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '96d5888b759f'
down_revision = '9848e3c12e0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('range', sa.Column('counter_max', sa.Integer(), nullable=True))
    op.add_column('range', sa.Column('counter_min', sa.Integer(), nullable=True))
    op.drop_column('range', 'counter')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('range', sa.Column('counter', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('range', 'counter_min')
    op.drop_column('range', 'counter_max')
    # ### end Alembic commands ###
