"""adding min max values to baseline

Revision ID: bd7ef1dd11c6
Revises: c68fa033b675
Create Date: 2020-07-20 11:16:58.499982

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'bd7ef1dd11c6'
down_revision = 'c68fa033b675'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('baseline', sa.Column('max_value', sa.Float(), nullable=True, server_default=0.0))
    op.add_column('baseline', sa.Column('min_value', sa.Float(), nullable=True, server_default=0.0))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('baseline', 'min_value')
    op.drop_column('baseline', 'max_value')
    # ### end Alembic commands ###
