"""fields for improved spotify queueing

Revision ID: c68fa033b675
Revises: 200a6d6bf142
Create Date: 2020-07-03 11:53:34.170164

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'c68fa033b675'
down_revision = '200a6d6bf142'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('result', sa.Column('action', sa.Integer(), nullable=True))
    op.add_column('result', sa.Column('song_plays_until', sa.DateTime(), nullable=True))
    op.add_column('result', sa.Column('song_queued', sa.Boolean(), nullable=True))
    op.add_column('song', sa.Column('duration', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('song', 'duration')
    op.drop_column('result', 'song_queued')
    op.drop_column('result', 'song_plays_until')
    op.drop_column('result', 'action')
    # ### end Alembic commands ###
