"""participants and songs

Revision ID: e78c91af2e12
Revises: ebb6e0e769ce
Create Date: 2020-04-08 11:35:36.830794

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'e78c91af2e12'
down_revision = 'ebb6e0e769ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_participants_id'), 'participants', ['id'], unique=False)
    op.create_table('songs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_songs_id'), 'songs', ['id'], unique=False)
    op.drop_index('ix_recordings_participant_id', table_name='recordings')
    op.drop_index('ix_recordings_total_time', table_name='recordings')
    op.create_foreign_key(None, 'recordings', 'participants', ['participant_id'], ['id'])
    op.drop_index('ix_results_run_id', table_name='results')
    op.drop_index('ix_runs_recording_id', table_name='runs')
    op.drop_index('ix_values_recording_id', table_name='values')
    op.drop_index('ix_values_timestamp', table_name='values')
    op.drop_index('ix_values_type', table_name='values')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_values_type', 'values', ['type'], unique=False)
    op.create_index('ix_values_timestamp', 'values', ['timestamp'], unique=False)
    op.create_index('ix_values_recording_id', 'values', ['recording_id'], unique=False)
    op.create_index('ix_runs_recording_id', 'runs', ['recording_id'], unique=False)
    op.create_index('ix_results_run_id', 'results', ['run_id'], unique=False)
    op.drop_constraint(None, 'recordings', type_='foreignkey')
    op.create_index('ix_recordings_total_time', 'recordings', ['total_time'], unique=False)
    op.create_index('ix_recordings_participant_id', 'recordings', ['participant_id'], unique=False)
    op.drop_index(op.f('ix_songs_id'), table_name='songs')
    op.drop_table('songs')
    op.drop_index(op.f('ix_participants_id'), table_name='participants')
    op.drop_table('participants')
    # ### end Alembic commands ###
