"""initial

Revision ID: ebb6e0e769ce
Revises: 
Create Date: 2020-04-07 16:48:07.891830

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'ebb6e0e769ce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recordings',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('participant_id', sa.Integer(), nullable=True),
                    sa.Column('total_time', sa.BigInteger(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_recordings_id'), 'recordings', ['id'], unique=False)
    op.create_index(op.f('ix_recordings_participant_id'), 'recordings', ['participant_id'], unique=False)
    op.create_index(op.f('ix_recordings_total_time'), 'recordings', ['total_time'], unique=False)
    op.create_table('runs',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('recording_id', sa.Integer(), nullable=True),
                    sa.Column('current_time', sa.BigInteger(), nullable=True),
                    sa.Column('is_running', sa.Boolean(), nullable=True),
                    sa.ForeignKeyConstraint(['recording_id'], ['recordings.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_runs_id'), 'runs', ['id'], unique=False)
    op.create_index(op.f('ix_runs_recording_id'), 'runs', ['recording_id'], unique=False)
    op.create_table('values',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('recording_id', sa.Integer(), nullable=True),
                    sa.Column('type', sa.Integer(), nullable=True),
                    sa.Column('timestamp', sa.BigInteger(), nullable=True),
                    sa.Column('value', sa.Float(), nullable=True),
                    sa.ForeignKeyConstraint(['recording_id'], ['recordings.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_values_id'), 'values', ['id'], unique=False)
    op.create_index(op.f('ix_values_recording_id'), 'values', ['recording_id'], unique=False)
    op.create_index(op.f('ix_values_timestamp'), 'values', ['timestamp'], unique=False)
    op.create_index(op.f('ix_values_type'), 'values', ['type'], unique=False)
    op.create_table('results',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('run_id', sa.Integer(), nullable=True),
                    sa.Column('timestamp', sa.BigInteger(), nullable=True),
                    sa.Column('song', sa.String(), nullable=True),
                    sa.Column('verdict', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_results_id'), 'results', ['id'], unique=False)
    op.create_index(op.f('ix_results_run_id'), 'results', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_results_run_id'), table_name='results')
    op.drop_index(op.f('ix_results_id'), table_name='results')
    op.drop_table('results')
    op.drop_index(op.f('ix_values_type'), table_name='values')
    op.drop_index(op.f('ix_values_timestamp'), table_name='values')
    op.drop_index(op.f('ix_values_recording_id'), table_name='values')
    op.drop_index(op.f('ix_values_id'), table_name='values')
    op.drop_table('values')
    op.drop_index(op.f('ix_runs_recording_id'), table_name='runs')
    op.drop_index(op.f('ix_runs_id'), table_name='runs')
    op.drop_table('runs')
    op.drop_index(op.f('ix_recordings_total_time'), table_name='recordings')
    op.drop_index(op.f('ix_recordings_participant_id'), table_name='recordings')
    op.drop_index(op.f('ix_recordings_id'), table_name='recordings')
    op.drop_table('recordings')
    # ### end Alembic commands ###
