"""added sensor model and a counter to baseline

Revision ID: f117c270e465
Revises: 6790c6d7fa8a
Create Date: 2020-06-08 15:47:54.934678

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = 'f117c270e465'
down_revision = '6790c6d7fa8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('baseline', sa.Column('counter', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('baseline', 'counter')
    # ### end Alembic commands ###
