"""added baseline and setting table

Revision ID: fdd2f1c3818b
Revises: 6ace944c1ceb
Create Date: 2020-05-14 09:52:10.112382

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'fdd2f1c3818b'
down_revision = '6ace944c1ceb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('setting',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('stress_threshold', sa.Float(), nullable=True),
                    sa.Column('acc_threshold', sa.Float(), nullable=True),
                    sa.Column('temp_threshold', sa.Float(), nullable=True),
                    sa.Column('eda_threshold', sa.Float(), nullable=True),
                    sa.Column('ibi_threshold', sa.Float(), nullable=True),
                    sa.Column('temp_latency', sa.Integer(), nullable=True),
                    sa.Column('duration', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_setting_id'), 'setting', ['id'], unique=False)
    op.create_table('baseline',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('sensor_id', sa.Integer(), nullable=True),
                    sa.Column('participant_id', sa.Integer(), nullable=True),
                    sa.Column('baseline', sa.Float(), nullable=True),
                    sa.ForeignKeyConstraint(['participant_id'], ['participant.id'], ),
                    sa.ForeignKeyConstraint(['sensor_id'], ['sensor.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_baseline_id'), 'baseline', ['id'], unique=False)
    op.drop_column('run', 'current_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('run', sa.Column('current_time', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_baseline_id'), table_name='baseline')
    op.drop_table('baseline')
    op.drop_index(op.f('ix_setting_id'), table_name='setting')
    op.drop_table('setting')
    # ### end Alembic commands ###
