version: '3.7'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
    expose:
      - "5432"

  queue:
    image: rabbitmq:3
    restart: always

  web:
    image: "dikohl/song-pulse"
    depends_on:
      - db
      - worker
    environment:
      - DATABASE_URL=postgres://docker:docker@db:5432/docker
      - SPOTIFY_CLIENT_ID=bcff380514c34d9c9e9c0f075368622f
      - SPOTIFY_CLIENT_SECRET=06abee92ed8e4b8180f1de73e6244ef9
      - SPOTIFY_REDIRECT_URI=http://130.60.24.99:8080/spotify/callback/
    ports:
      - "8080:8080"

  worker:
    image: 'dikohl/song-pulse-worker'
    depends_on:
      - db
      - queue
    environment:
      - DATABASE_URL=postgres://docker:docker@db:5432/docker
      - SPOTIFY_CLIENT_ID=bcff380514c34d9c9e9c0f075368622f
      - SPOTIFY_CLIENT_SECRET=06abee92ed8e4b8180f1de73e6244ef9
      - SPOTIFY_REDIRECT_URI=http://130.60.24.99:8080/spotify/callback/

  frontend:
    image: 'dikohl/song-pulse-frontend'
    depends_on:
      - web
    environment:
      - GATSBY_API_URL=http://130.60.24.99:8080/
    ports:
      - "8000:8000"