version: '3.7'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
    ports:
      - "8001:5432"

  queue:
    image: rabbitmq:3
    restart: always

  web:
    build:
      context: .
      dockerfile: backend.dockerfile
    image: "song-pulse"
    depends_on:
      - db
      - worker
    environment:
      - DATABASE_URL=postgres://docker:docker@db:5432/docker
    ports:
      - "8080:8080"

  worker:
    build:
      context: .
      dockerfile: celery.dockerfile
    image: 'song-pulse-worker'
    depends_on:
      - db
      - queue
    environment:
      - DATABASE_URL=postgres://docker:docker@db:5432/docker