name: Master - Testing

on:
  push:
    branches:
      - 'master'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose build db web
      - name:
        run: docker-compose up --no-deps -d db web
      - name: Test
        run: docker run --network container:web python -m unittest discover